baseURL = "https://blog.curtpoff.com"
languageCode = "en-us"
title = "Curt Poff"
theme = "LeaveIt"

paginate = 15
enableEmoji = false
enableRobotsTXT = true
googleAnalytics = ""
preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:filename/"

[menu]


  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

[params]
#    since = 2011
    author = "Curt Poff"
    avatar = "/androidify300.png"
    subtitle = "Web guy, beer drinker, sports fan"
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""

    description = "" # site description
    keywords = "" # site keywords

#    license= ''

[params.social]
    GitHub = "cpoff"
    Twitter = "cpoff"
    LinkedIn = "cpoff"
    Email   = "curt.poff@gmail.com"
    Instagram = "cpoff"
    Telegram = "cpoff"
#    Facebook = "xxoo"
#    Dribbble = "xxoo"
#    Medium = "xxoo"
#    Wechat = "/images/me/wechat.png"  # Wechat QRcode image
