baseURL = "https://example.com"
languageCode = "en-us"
title = "Curt Poff"
author = "Curt Poff"
theme = "vanilla"
googleAnalytics = ""
avatarurl = "/androidify300.jpg"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"
  categories = "categories"
  series = "series"

[permalinks]
  post = "/posts/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    pre = "edit"
    url = "/post/"
    weight = 20
#  [[menu.main]]
#    name = "Categories"
#    pre = "box"
#    url = "/categories/"
#    weight = 30
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 35
  [[menu.main]]
    name = "About"
    pre = "user"
    url = "/about/"
    weight = 40
  [[menu.main]]
    name = "Contact"
    pre = "mail"
    url = "/contact/"
    weight = 45
  [[menu.main]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 50

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Web guy, beer drinker, sports fan"
  footerText = ""
  hideFooter = false
