---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: static/uploads
public_path: https://blog.curtpoff.com/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=#{self.site_settings.engine_version}
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=#{self.site_settings.engine_version}
  preview_output_directory: public
  output_directory: public
version: '0.49'
