---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: https://hooks.zapier.com/hooks/catch/2230333/phybnk/
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: static/uploads
public_path: https://blog.curtpoff.com/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=#{self.site_settings.engine_version}
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=#{self.site_settings.engine_version}
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.49'
